# https://docs.rubocop.org/rubocop/configuration.html
require:
  - rubocop-rspec

AllCops:
  NewCops: enable

Metrics/BlockLength:
  Max: 50

Metrics/MethodLength:
  Max: 20

Metrics/ParameterLists:
  Max: 10

RSpec/MultipleExpectations:
  Max: 3