version: "3.9"

services:
  demo:
    build:
      context: ./
    ports:
      - "${FIBSCALE_PORT:-3000}:3000"

  fib:
    build:
      context: ./

  locust:
    image: locustio/locust:2.5.0
    environment:
      LOCUST_HOST: http://fib:3000
    ports:
      - "${FIBSCALE_LOCUST_PORT:-3001}:8089"
    volumes:
      - "./locustfile.py:/home/locust/locustfile.py:ro"
