name: build

on:
  push:
    branches:
      - '**/*'
  workflow_dispatch:

jobs:
  build:
    name: build
    runs-on: ubuntu-24.04
    steps:
      # https://github.com/actions/checkout
      - name: Checkout the repository
        uses: actions/checkout@v4

      # https://github.com/ruby/setup-ruby
      - name: Install ruby & dependencies
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Analyze source code
        run: |
          bundle exec rubocop

      - name: Ensure there are no uncommitted changes
        run: |
          git status --porcelain
          test -z "$(git status --porcelain)"
